
// File generated by FlutLab.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for iOS - '
          'try to add using FlutLab Firebase Configuration',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    authDomain: 'car-parking-d26dc.firebaseapp.com',
    projectId: 'car-parking-d26dc',
    storageBucket: 'car-parking-d26dc.firebasestorage.app',
    messagingSenderId: '818606882352',
    appId: '1:818606882352:web:6c42ab247083c33b4fb7f5',
    measurementId: 'G-2V5X09DNWQ'
  );

  static const FirebaseOptions android = FirebaseOptions(
    appId: '1:818606882352:android:478b5534cb0fafa14fb7f5',
    messagingSenderId: '818606882352',
    projectId: 'car-parking-d26dc',
    storageBucket: 'car-parking-d26dc.firebasestorage.app',
    authDomain: 'car-parking-d26dc.firebaseapp.com',
    measurementId: 'G-2V5X09DNWQ'
  );
}
